// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Vanus Connect Runtime Interface Document
//
//	this document describes the functions, parameters and return values of the vanus connect runtime API
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api/v1
//	Version: v0.2.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
