// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ChatgptHandlerFunc turns a function with the right signature into a chatgpt handler
type ChatgptHandlerFunc func(ChatgptParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ChatgptHandlerFunc) Handle(params ChatgptParams) middleware.Responder {
	return fn(params)
}

// ChatgptHandler interface for that can handle valid chatgpt params
type ChatgptHandler interface {
	Handle(ChatgptParams) middleware.Responder
}

// NewChatgpt creates a new http.Handler for the chatgpt operation
func NewChatgpt(ctx *middleware.Context, handler ChatgptHandler) *Chatgpt {
	return &Chatgpt{Context: ctx, Handler: handler}
}

/*
	Chatgpt swagger:route POST /source/chatgpt/{connector_id} connector chatgpt

source chatgpt connector request
*/
type Chatgpt struct {
	Context *middleware.Context
	Handler ChatgptHandler
}

func (o *Chatgpt) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewChatgptParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
