// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vanus-labs/vanus-connect-runtime/api/models"
)

// ChatgptOKCode is the HTTP code returned for type ChatgptOK
const ChatgptOKCode int = 200

/*
ChatgptOK OK

swagger:response chatgptOK
*/
type ChatgptOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewChatgptOK creates ChatgptOK with default headers values
func NewChatgptOK() *ChatgptOK {

	return &ChatgptOK{}
}

// WithPayload adds the payload to the chatgpt o k response
func (o *ChatgptOK) WithPayload(payload *models.APIResponse) *ChatgptOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chatgpt o k response
func (o *ChatgptOK) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChatgptOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
