// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ChataiHandlerFunc turns a function with the right signature into a chatai handler
type ChataiHandlerFunc func(ChataiParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ChataiHandlerFunc) Handle(params ChataiParams) middleware.Responder {
	return fn(params)
}

// ChataiHandler interface for that can handle valid chatai params
type ChataiHandler interface {
	Handle(ChataiParams) middleware.Responder
}

// NewChatai creates a new http.Handler for the chatai operation
func NewChatai(ctx *middleware.Context, handler ChataiHandler) *Chatai {
	return &Chatai{Context: ctx, Handler: handler}
}

/*
	Chatai swagger:route POST /source/chatai/{connector_id} connector chatai

source chatai connector request
*/
type Chatai struct {
	Context *middleware.Context
	Handler ChataiHandler
}

func (o *Chatai) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewChataiParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
