// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewChataiParams creates a new ChataiParams object
//
// There are no default values defined in the spec.
func NewChataiParams() ChataiParams {

	return ChataiParams{}
}

// ChataiParams contains all the bound params for the chatai operation
// typically these are obtained from a http.Request
//
// swagger:parameters chatai
type ChataiParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the chatai connector id
	  Required: true
	  In: path
	*/
	ConnectorID string
	/*
	  Required: true
	  In: body
	*/
	Message string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewChataiParams() beforehand.
func (o *ChataiParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rConnectorID, rhkConnectorID, _ := route.Params.GetOK("connector_id")
	if err := o.bindConnectorID(rConnectorID, rhkConnectorID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("message", "body", ""))
			} else {
				res = append(res, errors.NewParseError("message", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.Message = body
		}
	} else {
		res = append(res, errors.Required("message", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindConnectorID binds and validates parameter ConnectorID from path.
func (o *ChataiParams) bindConnectorID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ConnectorID = raw

	return nil
}
