// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChatGPT chatgpt message
//
// swagger:model ChatGPT
type ChatGPT struct {

	// chatgpt message
	Message string `json:"message,omitempty"`
}

// Validate validates this chat g p t
func (m *ChatGPT) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chat g p t based on context it is used
func (m *ChatGPT) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChatGPT) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatGPT) UnmarshalBinary(b []byte) error {
	var res ChatGPT
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
